# Define the new session name
$newSessionName = "test-ubuntu2"

# Path to the PuTTY sessions in the registry
$registryPath = "HKCU:\Software\SimonTatham\PuTTY\Sessions"
$newSessionPath = "$registryPath\$newSessionName"

# Create a new session key in the registry
New-Item -Path $newSessionPath -Force

# Function to set a registry item property
function Set-RegistryProperty {
    param($path, $name, $value, $type)
    Set-ItemProperty -Path $path -Name $name -Value $value -Type $type
}

# Set session parameters
Set-RegistryProperty -path $newSessionPath -name "Present" -value 1 -type DWord
# Set-RegistryProperty -path $newSessionPath -name "HostName" -value "192.168.137.136" -type String
Set-RegistryProperty -path $newSessionPath -name "LogFileName" -value "putty.log" -type String
Set-RegistryProperty -path $newSessionPath -name "LogType" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "LogFileClash" -value 0xFFFFFFFF -type DWord
Set-RegistryProperty -path $newSessionPath -name "LogFlush" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "LogHeader" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "SSHLogOmitPasswords" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "SSHLogOmitData" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "Protocol" -value "ssh" -type String
Set-RegistryProperty -path $newSessionPath -name "PortNumber" -value 22 -type DWord
Set-RegistryProperty -path $newSessionPath -name "CloseOnExit" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "WarnOnClose" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "PingInterval" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "PingIntervalSecs" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "TCPNoDelay" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "TCPKeepalives" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "TerminalType" -value "xterm" -type String
Set-RegistryProperty -path $newSessionPath -name "TerminalSpeed" -value "38400,38400" -type String
Set-RegistryProperty -path $newSessionPath -name "TerminalModes" -value "CS7=A,CS8=A,DISCARD=A,DSUSP=A,ECHO=A,ECHOCTL=A,ECHOE=A,ECHOK=A,ECHOKE=A,ECHONL=A,EOF=A,EOL=A,EOL2=A,ERASE=A,FLUSH=A,ICANON=A,ICRNL=A,IEXTEN=A,IGNCR=A,IGNPAR=A,IMAXBEL=A,INLCR=A,INPCK=A,INTR=A,ISIG=A,ISTRIP=A,IUCLC=A,IUTF8=A,IXANY=A,IXOFF=A,IXON=A,KILL=A,LNEXT=A,NOFLSH=A,OCRNL=A,OLCUC=A,ONLCR=A,ONLRET=A,ONOCR=A,OPOST=A,PARENB=A,PARMRK=A,PARODD=A,PENDIN=A,QUIT=A,REPRINT=A,START=A,STATUS=A,STOP=A,SUSP=A,SWTCH=A,TOSTOP=A,WERASE=A,XCASE=A" -type String
Set-RegistryProperty -path $newSessionPath -name "AddressFamily" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "ProxyExcludeList" -value "" -type String
Set-RegistryProperty -path $newSessionPath -name "ProxyDNS" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "ProxyLocalhost" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "ProxyMethod" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "ProxyHost" -value "proxy" -type String
Set-RegistryProperty -path $newSessionPath -name "ProxyPort" -value 80 -type DWord
Set-RegistryProperty -path $newSessionPath -name "ProxyUsername" -value "" -type String
Set-RegistryProperty -path $newSessionPath -name "ProxyPassword" -value "" -type String
Set-RegistryProperty -path $newSessionPath -name "ProxyTelnetCommand" -value "connect %host %port\n" -type String
Set-RegistryProperty -path $newSessionPath -name "ProxyLogToTerm" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "Environment" -value "" -type String
Set-RegistryProperty -path $newSessionPath -name "UserName" -value "" -type String
Set-RegistryProperty -path $newSessionPath -name "UserNameFromEnvironment" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "LocalUserName" -value "" -type String
Set-RegistryProperty -path $newSessionPath -name "NoPTY" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "Compression" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "TryAgent" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "AgentFwd" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "GssapiFwd" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "ChangeUsername" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "Cipher" -value "aes,chacha20,3des,WARN,des,blowfish,arcfour" -type String
Set-RegistryProperty -path $newSessionPath -name "KEX" -value "ecdh,dh-gex-sha1,dh-group14-sha1,rsa,WARN,dh-group1-sha1" -type String
Set-RegistryProperty -path $newSessionPath -name "HostKey" -value "ed25519,ecdsa,rsa,dsa,WARN" -type String
Set-RegistryProperty -path $newSessionPath -name "PreferKnownHostKeys" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "RekeyTime" -value 60 -type DWord
Set-RegistryProperty -path $newSessionPath -name "GssapiRekey" -value 2 -type DWord
Set-RegistryProperty -path $newSessionPath -name "RekeyBytes" -value "1G" -type String
Set-RegistryProperty -path $newSessionPath -name "SshNoAuth" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "SshBanner" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "AuthTIS" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "AuthKI" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "AuthGSSAPI" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "AuthGSSAPIKEX" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "GSSLibs" -value "gssapi32,sspi,custom" -type String
Set-RegistryProperty -path $newSessionPath -name "GSSCustom" -value "" -type String
Set-RegistryProperty -path $newSessionPath -name "SshNoShell" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "SshProt" -value 3 -type DWord
Set-RegistryProperty -path $newSessionPath -name "LogHost" -value "" -type String
Set-RegistryProperty -path $newSessionPath -name "SSH2DES" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "PublicKeyFile" -value "" -type String
Set-RegistryProperty -path $newSessionPath -name "RemoteCommand" -value "sudo docker run --rm -it --network host -v ~/.pcredz:/root/.pcredz snovvcrash/pcredz -i ens33" -type String
Set-RegistryProperty -path $newSessionPath -name "RFCEnviron" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "PassiveTelnet" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "BackspaceIsDelete" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "RXVTHomeEnd" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "LinuxFunctionKeys" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "NoApplicationKeys" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "NoApplicationCursors" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "NoMouseReporting" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "NoRemoteResize" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "NoAltScreen" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "NoRemoteWinTitle" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "NoRemoteClearScroll" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "RemoteQTitleAction" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "NoDBackspace" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "NoRemoteCharset" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "ApplicationCursorKeys" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "ApplicationKeypad" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "NetHackKeypad" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "AltF4" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "AltSpace" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "AltOnly" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "ComposeKey" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "CtrlAltKeys" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "TelnetKey" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "TelnetRet" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "LocalEcho" -value 2 -type DWord
Set-RegistryProperty -path $newSessionPath -name "LocalEdit" -value 2 -type DWord
Set-RegistryProperty -path $newSessionPath -name "Answerback" -value "PuTTY" -type String
Set-RegistryProperty -path $newSessionPath -name "AlwaysOnTop" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "FullScreenOnAltEnter" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "HideMousePtr" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "SunkenEdge" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "WindowBorder" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "CurType" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "BlinkCur" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "Beep" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "BeepInd" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "BellWaveFile" -value "" -type String
Set-RegistryProperty -path $newSessionPath -name "BellOverload" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "BellOverloadN" -value 5 -type DWord
Set-RegistryProperty -path $newSessionPath -name "BellOverloadT" -value 2000 -type DWord
Set-RegistryProperty -path $newSessionPath -name "BellOverloadS" -value 5000 -type DWord
Set-RegistryProperty -path $newSessionPath -name "ScrollbackLines" -value 2000 -type DWord
Set-RegistryProperty -path $newSessionPath -name "DECOriginMode" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "AutoWrapMode" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "LFImpliesCR" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "CRImpliesLF" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "DisableArabicShaping" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "DisableBidi" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "WinNameAlways" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "WinTitle" -value "" -type String
Set-RegistryProperty -path $newSessionPath -name "TermWidth" -value 80 -type DWord
Set-RegistryProperty -path $newSessionPath -name "TermHeight" -value 24 -type DWord
Set-RegistryProperty -path $newSessionPath -name "Font" -value "Courier New" -type String
Set-RegistryProperty -path $newSessionPath -name "FontIsBold" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "FontCharSet" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "FontHeight" -value 10 -type DWord
Set-RegistryProperty -path $newSessionPath -name "FontQuality" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "FontVTMode" -value 4 -type DWord
Set-RegistryProperty -path $newSessionPath -name "UseSystemColours" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "TryPalette" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "ANSIColour" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "Xterm256Colour" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "TrueColour" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "BoldAsColour" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "BoldAsColour" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "Colour0" -value "187,187,187" -type String
Set-RegistryProperty -path $newSessionPath -name "Colour1" -value "255,255,255" -type String
Set-RegistryProperty -path $newSessionPath -name "Colour2" -value "0,0,0" -type String
Set-RegistryProperty -path $newSessionPath -name "Colour3" -value "85,85,85" -type String
Set-RegistryProperty -path $newSessionPath -name "Colour4" -value "0,0,0" -type String
Set-RegistryProperty -path $newSessionPath -name "Colour5" -value "0,255,0" -type String
Set-RegistryProperty -path $newSessionPath -name "Colour6" -value "0,0,0" -type String
Set-RegistryProperty -path $newSessionPath -name "Colour7" -value "85,85,85" -type String
Set-RegistryProperty -path $newSessionPath -name "Colour8" -value "187,0,0" -type String
Set-RegistryProperty -path $newSessionPath -name "Colour9" -value "255,85,85" -type String
Set-RegistryProperty -path $newSessionPath -name "Colour10" -value "0,187,0" -type String
Set-RegistryProperty -path $newSessionPath -name "Colour11" -value "85,255,85" -type String
Set-RegistryProperty -path $newSessionPath -name "Colour12" -value "187,187,0" -type String
Set-RegistryProperty -path $newSessionPath -name "Colour13" -value "255,255,85" -type String
Set-RegistryProperty -path $newSessionPath -name "Colour14" -value "0,0,187" -type String
Set-RegistryProperty -path $newSessionPath -name "Colour15" -value "85,85,255" -type String
Set-RegistryProperty -path $newSessionPath -name "Colour16" -value "187,0,187" -type String
Set-RegistryProperty -path $newSessionPath -name "Colour17" -value "255,85,255" -type String
Set-RegistryProperty -path $newSessionPath -name "Colour18" -value "0,187,187" -type String
Set-RegistryProperty -path $newSessionPath -name "Colour19" -value "85,255,255" -type String
Set-RegistryProperty -path $newSessionPath -name "Colour20" -value "187,187,187" -type String
Set-RegistryProperty -path $newSessionPath -name "Colour21" -value "255,255,255" -type String
Set-RegistryProperty -path $newSessionPath -name "RawCNP" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "UTF8linedraw" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "PasteRTF" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "MouseIsXterm" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "RectSelect" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "PasteControls" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "MouseOverride" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "Wordness0" -value "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0" -type String
Set-RegistryProperty -path $newSessionPath -name "Wordness32" -value "0,1,2,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1" -type String
Set-RegistryProperty -path $newSessionPath -name "Wordness64" -value "1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,2" -type String
Set-RegistryProperty -path $newSessionPath -name "Wordness96" -value "1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1" -type String
Set-RegistryProperty -path $newSessionPath -name "Wordness128" -value "1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" -type String
Set-RegistryProperty -path $newSessionPath -name "Wordness160" -value "1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1" -type String
Set-RegistryProperty -path $newSessionPath -name "Wordness192" -value "2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2" -type String
Set-RegistryProperty -path $newSessionPath -name "Wordness224" -value "2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2" -type String
Set-RegistryProperty -path $newSessionPath -name "MouseAutocopy" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "MousePaste" -value "explicit" -type String
Set-RegistryProperty -path $newSessionPath -name "CtrlShiftIns" -value "explicit" -type String
Set-RegistryProperty -path $newSessionPath -name "CtrlShiftCV" -value "none" -type String
Set-RegistryProperty -path $newSessionPath -name "LineCodePage" -value "" -type String
Set-RegistryProperty -path $newSessionPath -name "CJKAmbigWide" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "UTF8Override" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "Printer" -value "" -type String
Set-RegistryProperty -path $newSessionPath -name "CapsLockCyr" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "ScrollBar" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "ScrollBarFullScreen" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "ScrollOnKey" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "ScrollOnDisp" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "EraseToScrollback" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "LockSize" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "BCE" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "BlinkText" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "X11Forward" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "X11Display" -value "" -type String
Set-RegistryProperty -path $newSessionPath -name "X11AuthType" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "X11AuthFile" -value "" -type String
Set-RegistryProperty -path $newSessionPath -name "LocalPortAcceptAll" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "RemotePortAcceptAll" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "PortForwardings" -value "" -type String
Set-RegistryProperty -path $newSessionPath -name "BugIgnore1" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "BugPlainPW1" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "BugRSA1" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "BugIgnore2" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "BugHMAC2" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "BugDeriveKey2" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "BugRSAPad2" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "BugPKSessID2" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "BugRekey2" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "BugMaxPkt2" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "BugOldGex2" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "BugWinadj" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "BugChanReq" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "StampUtmp" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "LoginShell" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "ScrollbarOnLeft" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "BoldFont" -value "" -type String
Set-RegistryProperty -path $newSessionPath -name "BoldFontIsBold" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "BoldFontCharSet" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "BoldFontHeight" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "WideFont" -value "" -type String
Set-RegistryProperty -path $newSessionPath -name "WideFontIsBold" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "WideFontCharSet" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "WideFontHeight" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "WideBoldFont" -value "" -type String
Set-RegistryProperty -path $newSessionPath -name "WideBoldFontIsBold" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "WideBoldFontCharSet" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "WideBoldFontHeight" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "ShadowBold" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "ShadowBoldOffset" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "SerialLine" -value "COM1" -type String
Set-RegistryProperty -path $newSessionPath -name "SerialSpeed" -value 9600 -type DWord
Set-RegistryProperty -path $newSessionPath -name "SerialDataBits" -value 8 -type DWord
Set-RegistryProperty -path $newSessionPath -name "SerialStopHalfbits" -value 2 -type DWord
Set-RegistryProperty -path $newSessionPath -name "SerialParity" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "SerialFlowControl" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "WindowClass" -value "" -type String
Set-RegistryProperty -path $newSessionPath -name "ConnectionSharing" -value 0 -type DWord
Set-RegistryProperty -path $newSessionPath -name "ConnectionSharingUpstream" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "ConnectionSharingDownstream" -value 1 -type DWord
Set-RegistryProperty -path $newSessionPath -name "SSHManualHostKeys" -value "" -type String

# Output to indicate completion
Write-Host "Session '$newSessionName' created successfully."